### ISSUE TITLE
Graphite: Rendering reph in a cluster of four (or more) consonants

### ISSUE THREAD

**Issue by jcoblentz** [silnrsi/font-annapurna#2]
An email from a tester:

I'm afraid that in my testing I discovered another bug. This one was present in all previous versions, right from 1.00, so is not new, but I never noticed it before. It shows up when we have a cluster of four (or more) consonants where the first one is ra so displays as reph. The reph should be positioned on the final consonant of the cluster (or its vowel, if it has a spacing vowel such as aakar, okar, etc). This works for up to three consonants, eg a word like 'parksa' or 'parksaa' ... (See attached screenshot because correct rendering does not happen here.)

![annapurna graphite rendering reph in a cluster of four or more consonants](https://user-images.githubusercontent.com/12460265/30327645-cc5a160c-979a-11e7-9a30-9579a683af85.jpg)

12-Sept-2017

**Comment by mhosken** [comment]
This looks like it _may_ be the same root cause as issue #1. Which is that for rules that advance the 'current cursor' through the environment, rather than making the last rhs slot be the one before the output current cursor, the engine can lose track and not notice it is making progress. It will then jump 5 rules later regardless of the fact that it shouldn't.

**Comment by jcoblentz** [comment]
Fixed Sept. 2017
